Categories index command
rapidez/core pull request #243
Opened 2023-04-21 08:32 UTC by Jade-GG

Because this is getting re-used all over the place.

2023-04-25 15:06 UTC, royduin commented
Thanks! Looking forward to the implementation in the autocomplete 😇

2023-04-25 15:12 UTC, royduin requested changes

2023-04-25 15:12 UTC, royduin commented on src/Commands/IndexCategoriesCommand.php
> +        : $storeModel::all();
```suggestion
        $stores = $this->argument('store')
            ? $storeModel::where('store_id', $this->argument('store'))->get()
            : $storeModel::all();
```

2023-04-25 15:12 UTC, royduin commented on src/Commands/IndexCategoriesCommand.php
> +    }
Can we extract this somewhere so we can benefit from this everywhere? Could also be used within the products index command.

2023-04-25 15:12 UTC, royduin commented on src/Commands/IndexCategoriesCommand.php
> +            $data = config('rapidez.models.category')::select($categoryModelInstance->qualifyColumns(['entity_id', 'name', 'url_path', 'children_count']))
This is pretty static now, maybe add the possibility to change/extend this with for example an Eventy filter

2023-04-25 15:12 UTC, royduin commented on src/Commands/IndexCategoriesCommand.php
> +                ->where('children_count', '>', 0)
So categories without child categories won't be indexed? Why?

2023-05-15 11:07 UTC, Jade-GG commented
waiting for https://github.com/rapidez/core/pull/254 for now :)

2023-06-16 08:04 UTC, royduin commented
#254 is merged 🚀

2023-06-19 05:52 UTC, Jade-GG commented
https://github.com/rapidez/core/pull/280 😇

2023-06-19 05:52 UTC, closed without merging