Listen to all customer address configuration
rapidez/core pull request #373
Opened 2023-11-03 10:28 UTC by indykoning

2023-11-03 11:02 UTC, royduin commented on resources/views/checkout/partials/address.blade.php
> +                        {{ __($suffix) }}
```suggestion
                        @lang($suffix)
```

2023-11-03 11:02 UTC, royduin commented on resources/views/checkout/partials/address.blade.php
> +                        {{ __($prefix) }}
```suggestion
                        @lang($prefix)
```

2023-11-03 11:06 UTC, royduin submitted a review, later dismissed

2023-11-03 12:26 UTC, Jade-GG requested changes

2023-11-03 12:26 UTC, Jade-GG commented on resources/views/checkout/partials/address.blade.php
> +                @if(Rapidez::config('customer/address/prefix_show', false) === 'opt')
Two different defaults? 😇

2023-11-03 12:26 UTC, Jade-GG commented on resources/views/checkout/partials/address.blade.php
> +                @if(Rapidez::config('customer/address/suffix_show', false) === 'opt')
Same here ^

2023-11-03 12:26 UTC, Jade-GG commented on src/Http/ViewComposers/ConfigComposer.php
> +            'suffix'      => strlen(Rapidez::config('customer/address/suffix_options', '')) ? Rapidez::config('customer/address/prefix_show', 'opt') : 'opt',
should be `suffix_show` here

2023-11-07 09:04 UTC, Jade-GG commented
Defaults are still `'opt'` in one place (required prop) and `''` in the other, which one is the correct default for these?

2023-11-07 13:26 UTC, Jade-GG approved these changes

2023-11-07 13:44 UTC, indykoning commented
That is correct, in validation we would want it to be optional if it wouldn't be shown. But in showing the actual field we want to listen to all options by default

2023-11-07 15:17 UTC, royduin approved these changes

2023-11-07 15:18 UTC, merged