[3.x] Split up quantity select into 2 variants
rapidez/core pull request #608
Opened 2024-10-22 07:55 UTC by BobWez98

V3 PR for #595

2024-11-06 10:35 UTC, indykoning approved these changes

2024-11-15 14:33 UTC, royduin requested changes
Thanks but I'm not really happy how this turns out, I tried to address some issues with https://github.com/rapidez/core/pull/645. Thoughts?

2024-11-15 14:33 UTC, royduin commented on resources/js/components/Product/QuantitySelect.vue
> +            let input = this.$scopedSlots.default()[0].context.$refs[this.inputRef]
This should be possible without the ref, this is an anti pattern

2024-11-15 14:33 UTC, royduin commented on resources/js/components/Product/QuantitySelect.vue
> +        defaultQty: {
This isn't used?

2024-11-15 14:33 UTC, royduin commented on resources/views/cart/item/quantity.blade.php
> +        <x-rapidez::quantity @change="mutate" index="item.id" model="variables.quantity" minSaleQty="(item.product.stock_item?.min_sale_qty ?? 1)" qtyIncrements="(item.product.stock_item?.qty_increme
The `max_sale_qty` is missing here

2024-11-15 14:33 UTC, royduin commented on resources/views/components/quantity/enhanced.blade.php
> +<quantity-select :input-ref="'qty-select-' + {{ $index }}" :model="parseInt({{ $model }})" :min-qty="{{ $minSaleQty }}" :increment="{{ $qtyIncrements }}" v-slot="qtySelect">
This feels odd passing through the props

2024-11-15 14:33 UTC, royduin commented on resources/views/components/quantity/enhanced.blade.php
> +        <x-rapidez::button.outline @click.prevent="qtySelect.decrease">
It isn't getting disabled when you can't decrease due the min qty

2024-11-15 14:33 UTC, royduin commented on resources/views/components/quantity/enhanced.blade.php
> +            :label="false"
This input isn't described now which is required for accessibility

2024-11-15 14:33 UTC, royduin commented on resources/views/components/quantity/index.blade.php
This version isn't used, let's stick with 1 version.

2024-11-15 14:33 UTC, royduin commented on resources/views/product/partials/grouped.blade.php
> +                    @include('rapidez::product.partials.quantity.default', ['product' => $groupedProduct])
This file doesn't exist

2024-12-04 07:34 UTC, royduin commented
Closing this in favor of https://github.com/rapidez/core/pull/645

2024-12-04 07:34 UTC, closed without merging